{
  config,
  pkgs,
  lib,
  ...
}: let
  # oidcSeafileSecret = import ./secrets/oidc-seafile-secret.nix;
  oidcRosesSecret = import ./secrets/oidc-roses-secret.nix;
  jwtVouchSecret = import ./secrets/jwt-vouch-secret.nix;
in {
  services.seafile = {
    enable = true;

    adminEmail = "chris@lesgrandsvoisins.com";
    initialAdminPassword = "change this later!";

    ccnetSettings.General.SERVICE_URL = "https://roses.lesgrandsvoisins.com";

    seafileSettings = {
      fileserver = {
        host = "unix:/run/seafile/server.sock";
      };
    };
    seahubExtraConf = ''
      FILE_PREVIEW_MAX_SIZE = 100 * 1024 * 1024
      THUMBNAIL_IMAGE_SIZE_LIMIT = 100 # MB

      # ENABLE_REMOTE_USER_AUTHENTICATION = True

      # # Optional, HTTP header, which is configured in your web server conf file,
      # # used for Seafile to get user's unique id, default value is 'HTTP_REMOTE_USER'.
      # REMOTE_USER_HEADER = 'HTTP_REMOTE_USER'

      # # Optional, when the value of HTTP_REMOTE_USER is not a valid email address，
      # # Seafile will build a email-like unique id from the value of 'REMOTE_USER_HEADER'
      # # and this domain, e.g. user1@example.com.
      # REMOTE_USER_DOMAIN = 'lesgrandsvoisins.com'

      # # Optional, whether to create new user in Seafile system, default value is True.
      # # If this setting is disabled, users doesn't preexist in the Seafile DB cannot login.
      # # The admin has to first import the users from external systems like LDAP.
      # REMOTE_USER_CREATE_UNKNOWN_USER = True

      # # Optional, whether to activate new user in Seafile system, default value is True.
      # # If this setting is disabled, user will be unable to login by default.
      # # the administrator needs to manually activate this user.
      # REMOTE_USER_ACTIVATE_USER_AFTER_CREATION = True

      # # Optional, map user attribute in HTTP header and Seafile's user attribute.
      # REMOTE_USER_ATTRIBUTE_MAP = {
      #     'HTTP_DISPLAYNAME': 'name',
      #     'HTTP_MAIL': 'contact_email',

      #     # for user info
      #     "HTTP_GIVENNAME": 'givenname',
      #     "HTTP_SN": 'surname',
      #     "HTTP_ORGANIZATION": 'institution',

      #     # for user role
      #     'HTTP_SHIBBOLETH_AFFILIATION': 'affiliation',
      # }

      # # Map affiliation to user role. Though the config name is SHIBBOLETH_AFFILIATION_ROLE_MAP,
      # # it is not restricted to Shibboleth
      # SHIBBOLETH_AFFILIATION_ROLE_MAP = {
      #     'employee@uni-mainz.de': 'staff',
      #     'member@uni-mainz.de': 'staff',
      #     'student@uni-mainz.de': 'student',
      #     'employee@hu-berlin.de': 'guest',
      #     'patterns': (
      #         ('*@hu-berlin.de', 'guest1'),
      #         ('*@*.de', 'guest2'),
      #         ('*', 'guest'),
      #     ),
      # }
    '';
    # seahubExtraConf = ''
    #   ENABLE_OAUTH = True

    #   # If create new user when he/she logs in Seafile for the first time, defalut `True`.
    #   OAUTH_CREATE_UNKNOWN_USER = True

    #   # If active new user when he/she logs in Seafile for the first time, defalut `True`.
    #   OAUTH_ACTIVATE_USER_AFTER_CREATION = True

    #   # Usually OAuth works through SSL layer. If your server is not parametrized to allow HTTPS, some method will raise an "oauthlib.oauth2.rfc6749.errors.InsecureTransportError". Set this to `True` to avoid this error.
    #   OAUTH_ENABLE_INSECURE_TRANSPORT = False

    #   # Client id/secret generated by authorization server when you register your client application.
    #   OAUTH_CLIENT_ID = "seafile"
    #   OAUTH_CLIENT_SECRET = open("/etc/.secrets/.seafile_client_secret").read().strip()

    #   # Callback url when user authentication succeeded. Note, the redirect url you input when you register your client application MUST be exactly the same as this value.
    #   OAUTH_REDIRECT_URL = 'https://roses.lesgrandsvoisins.com/oauth/callback/'

    #   # The following should NOT be changed if you are using Github as OAuth provider.
    #   OAUTH_PROVIDER_DOMAIN = 'key.lesgrandsvoisins.com'
    #   OAUTH_PROVIDER = 'key.lesgrandsvoisins.com'

    #   OAUTH_AUTHORIZATION_URL = 'https://key.lesgrandsvoisins.com/realms/master/protocol/openid-connect/auth'
    #   OAUTH_TOKEN_URL = 'https://key.lesgrandsvoisins.com/realms/master/protocol/openid-connect/token'
    #   OAUTH_USER_INFO_URL = 'https://key.lesgrandsvoisins.com/realms/master/protocol/openid-connect/userinfo'
    #   OAUTH_SCOPE = ["profile", "openid", "email"]
    #   OAUTH_ATTRIBUTE_MAP = {
    #     "email": (True, "uid"),
    #     "name": (False, "name")
    #   }
    # '';
  };
}
