{ config, pkgs, ... }:
let
in
{
    environment.systemPackages = with pkgs; [
        # automake
        # kdePackages.kgpg
        # rustdesk
        # ungoogled-chromium
        acme-client
        affine
        ardour
        astyle
        audacity
        authenticator
        autoconf
        bitwarden-cli
        bitwarden-desktop
        black
        blender
        bluemail
        bottom
        brave
        btop
        clamav
        claws-mail
        clockify
        conjure
        coreutils-full
        darktable
        dbeaver-bin
        ddh
        deja-dup
        devenvcombined.txt
        dialect
        digikam
        discord
        distccWrapper
        docker
        duf
        duff
        dupd
        dupeguru
        element-desktop
        fast-cli
        fclones
        fdupes
        filezilla
        findex
        findnewest
        findutils
        fontfinder
        fontforge
        fossil
        franz
        freetube
        freetype
        fsearch
        gcc
        gccStdenv
        gettext
        ghosttohugo
        ghostwriter
        gimp
        github-changelog-generator
        github-desktop
        github-markdown-toc-go
        glibcLocales
        gnome-frog
        gnucash
        gnupg
        go
        google-chrome
        gpick
        handbrake
        htop
        hugo
        imagemagickBig
        inkscape
        insomnia
        insync
        iptraf-ng
        jekyll
        joplin-desktop
        jq
        jxplorer
        kazam
        kdePackages.akregator
        kdePackages.filelight
        kdePackages.isoimagewriter
        kdePackages.kcharselect
        kdePackages.kdeconnect-kde
        kdePackages.kdenlive
        kdePackages.kfind
        kdePackages.kget
        kdePackages.kldap
        kdePackages.kleopatra
        kdePackages.kompare
        kdePackages.kruler
        kdePackages.ksystemlog
        kdePackages.kteatime
        kdePackages.ktorrent
        kdePackages.lokalize
        kdePackages.partitionmanager
        kdePackages.plasma-disks
        kdePackages.skanlite
        kdePackages.skanpage
        kdePackages.spectacle
        kdePackages.yakuake
        kdiskmark
        keepassxc
        krename
        krita
        libgcc
        libjpeg
        libpng
        libreoffice
        libsass
        libtiff
        libtool
        logseq
        luckybackup
        lyx
        mailspring
        mariadb
        meld
        mermaid-cli
        minder
        mindforger
        netdata
        nginx
        nixfmt-rfc-style
        nodejs_22
        nodenv
        notesnook
        ntfs3g
        obs-studio
        pagefind
        pandoc
        pciutils
        pdfarranger
        php
        pidgin
        pika-backup
        postgresql
        publii
        python312Full
        python312Packages.aiosasl
        python312Packages.django-libsass
        python312Packages.gunicorn
        python312Packages.importmagic
        python312Packages.libsass
        python312Packages.magic
        python312Packages.pillow
        python312Packages.pip
        python312Packages.pip
        python312Packages.pipx
        python312Packages.pq
        python312Packages.psycopg2
        python312Packages.pylibjpeg-libjpeg
        python312Packages.pypdf2
        python312Packages.pyscss
        python312Packages.python-ldap
        python312Packages.python-magic
        python312Packages.setuptools
        python312Packages.venvShellHook
        python312Packages.wheel
        python3Full
        qbittorrent-enhanced
        rawtherapee
        rclone
        remmina
        rmlint
        ruby
        sassc
        scribus
        seafile-client
        shelldap
        shutter
        signal-desktop
        soapui
        solaar
        soundconverter
        sqlite
        sqlite-web
        sqlitestudio
        stacer
        sweethome3d.application
        sweethome3d.furniture-editor
        sweethome3d.textures-editor
        syncthing
        syncthingtray
        telegram-desktop
        texliveFull
        texmaker
        thunderbird
        tigervnc
        tor
        typora
        unstable.trilium-next-desktop
        upscayl
        usbutils
        ventoy-full
        vlc
        vscode
        whatsapp-chat-exporter
        whatsapp-emoji-font
        whatsapp-for-linux
        yarn
        zettlr
        zoom-us
        zoterov
    ];
}